name: Deploy to EC2
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to EC2 by using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/ubuntu/app
          git pull origin master
          docker stop halloword
          docker rm halloword
          cd program
          docker build -t donpebru/trial-hello:latest .
          docker run -d -e "HTTP_PORT=:8080" -p 8080:8080 --name halloword donpebru/trial-hello:latest